telemetry_mode: "none"
conn:
    # - 2
    # - 4
    # - 8
    # - 16
    # - 32
    # TODO: restore above back.
    - 64
qps:
    - 1000
duration: 240
metrics:
    - p50
    - p90
    - p99
perf_record: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true
extra_labels: "plaintext"