kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql-server
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mysql-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: "fast"
#   selector:
#     matchLabels:
#       release: dev
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: tmp-mysql-1
#   labels:
#     release: dev
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "fast"
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /tmp/mysql
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-server
#   labels:
#     app: mysql-server
# spec:
#   selector:
#     app: mysql-server
#   ports:
#   - port: 3306
#     name: tcp
#     protocol: TCP
# ---
# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: mysql-server
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: mysql-server
#     spec:
#       containers:
#       - name: mysql
#         image: mysql:5.7.22
#         imagePullPolicy: IfNotPresent
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "root"
#         ports:
#         - containerPort: 3306
#         volumeMounts:
#         - name: mysql-volume
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql-volume
#         persistentVolumeClaim:
#           claimName: mysql-pvc
#       restartPolicy: Always