apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: entrypoint
spec:
  gateways:
  - entrypoint-gateway
  hosts:
  - {{ .Values.serviceNamePrefix }}0.local
  - {{ .Values.serviceNamePrefix }}0.{{ .Values.domain }}
  http:
  - route:
    - destination:
        host: {{ .Values.serviceNamePrefix }}0
        port:
          number: 8080
        weight: 100

