apiVersion: v1
data:
  service-graph: |
    services:
    - isEntrypoint: true
      name: {{ .Values.serviceNamePrefix }}0
      numReplicas: {{ .Values.replicas }}
      responseSize: {{ .Values.responseSize }}
      script:
      - {{- range until (int .Values.automtls.serviceNumber) }}
        - call:
            service: {{ $.Values.serviceNamePrefix }}0-front-{{ . }}
            size: {{ $.Values.requestSize }}
        {{- end }}
      type: http
    {{- range until (int .Values.automtls.serviceNumber) }}
    - name: {{ $.Values.serviceNamePrefix }}0-front-{{ . }}
      numReplicas: {{ $.Values.replicas }}
      responseSize: {{ $.Values.responseSize }}
      script:
      - - call:
            service: {{ $.Values.serviceNamePrefix }}0-back-{{ . }}
            size: {{ $.Values.requestSize }}
      type: http
    - name: {{ $.Values.serviceNamePrefix }}0-back-{{ . }}
      numReplicas: {{ $.Values.replicas }}
      responseSize: {{ $.Values.responseSize }}
      type: http
    {{- end }}
kind: ConfigMap
metadata:
  labels:
    app: service-graph
  name: service-graph-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-graph
  name: {{ .Values.serviceNamePrefix }}0
spec:
  ports:
  - name: http-web
    port: 8080
  selector:
    app: {{ .Values.serviceNamePrefix }}0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-graph
  name: {{ .Values.serviceNamePrefix }}0v1
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.serviceNamePrefix }}0
  template:
    metadata:
      annotations:
{{- if .Values.prometheus_scrape }}
        prometheus.io/scrape: "true"
{{- end }}
      labels:
        app: {{ .Values.serviceNamePrefix }}0
        role: service
        version: v1
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=32
        env:
        - name: SERVICE_NAME
          value: {{ .Values.serviceNamePrefix }}0
        image: {{ .Values.serviceGraphImage }}
        name: mock-service
        ports:
        - containerPort: 8080
{{- if .Values.livenessProbe }}
        livenessProbe: {{ toJson .Values.livenessProbe }}
{{- end}}
{{- if .Values.readinessProbe }}
        readinessProbe: {{ toJson .Values.readinessProbe }}
{{- end}}
        resources: {{ toJson .Values.resources }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-graph
  name: {{ .Values.serviceNamePrefix }}0
spec:
  ports:
  - name: http-web
    port: 8080
  selector:
    app: {{ .Values.serviceNamePrefix }}0
---
{{range until (int .Values.automtls.serviceNumber) }}
{{- $sn := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-graph
  name: {{ $.Values.serviceNamePrefix }}0-front-{{ $sn }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: {{ $.Values.serviceNamePrefix }}0-front-{{ $sn }}
  template:
    metadata:
      annotations:
{{- if $.Values.prometheus_scrape }}
        prometheus.io/scrape: "true"
{{- end }}
      labels:
        app: {{ $.Values.serviceNamePrefix }}0-front-{{ $sn }}
        role: service
        version: v1
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=32
        env:
        - name: SERVICE_NAME
          value: {{ $.Values.serviceNamePrefix }}0-front-{{ $sn }}
        image: {{ $.Values.serviceGraphImage }}
        name: mock-service
        ports:
        - containerPort: 8080
{{- if $.Values.livenessProbe }}
        livenessProbe: {{ toJson $.Values.livenessProbe }}
{{- end}}
{{- if $.Values.readinessProbe }}
        readinessProbe: {{ toJson $.Values.readinessProbe }}
{{- end}}
        resources: {{ toJson $.Values.resources }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-graph
  name: {{ $.Values.serviceNamePrefix }}0-front-{{ $sn }}
spec:
  ports:
  - name: http-web
    port: 8080
  selector:
    app: {{ $.Values.serviceNamePrefix }}0-front-{{ $sn }}
status:
---
{{- range $name := list "istio" "legacy" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-graph
  name: {{ $.Values.serviceNamePrefix }}0-back-{{ $sn }}-{{$name}}
spec:
  # Half of each state of the deployment.
  replicas: {{ div $.Values.automtls.backendReplicas 2 }}
  selector:
    matchLabels:
      app: {{ $.Values.serviceNamePrefix }}0-back-{{ $sn }}
  template:
    metadata:
      annotations:
{{- if eq $name "legacy" }}
        sidecar.istio.io/inject: "false"
{{- end}}
{{- if $.Values.prometheus_scrape }}
        prometheus.io/scrape: "true"
{{- end }}
      labels:
        app: {{ $.Values.serviceNamePrefix }}0-back-{{ $sn }}
        role: service
        version: v1
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=32
        env:
        - name: SERVICE_NAME
          value: {{ $.Values.serviceNamePrefix }}0-back-{{ $sn }}
        image: {{ $.Values.serviceGraphImage }}
        name: mock-service
        ports:
        - containerPort: 8080
{{- if $.Values.livenessProbe }}
        livenessProbe: {{ toJson $.Values.livenessProbe }}
{{- end}}
{{- if $.Values.readinessProbe }}
        readinessProbe: {{ toJson $.Values.readinessProbe }}
{{- end}}
        resources: {{ toJson $.Values.resources }}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-graph
  name: {{ $.Values.serviceNamePrefix }}0-back-{{ $sn }}
spec:
  ports:
  - name: http-web
    port: 8080
  selector:
    app: {{ $.Values.serviceNamePrefix }}0-back-{{ $sn }}
status:
{{end}}
---
